# this is generated by cyberdog
def get_config_test():
	return {'a': {'a': 1, 'b': 'cyberdog', 'c': True, 'd': 0.1}, 'b': [{'a': 1, 'b': 'cyberdog', 'c': True, 'd': 0.1}, {'a': 2, 'b': 'robotlab', 'c': False, 'd': 0.2}]}