import benchmark
import toml

# def hello():
#     print("Cpp function call helle python")
#
#
#
# data = toml.load('benchmark.toml')
# print(toml.dumps(data))
#
# tdata = toml.dumps(data)
# hpp_file = "test.pyx"
# with open(hpp_file, 'w') as f:
#     f.write("# cython: language_level=3 \n")
#     f.write("# this is generated by python scripts.\n")
#     # f.write("\treturn " + "\"" + str(data) + "\"")
#     f.write("\treturn " +  str(tdata))

# data = benchmark.get_benchmark_data()
# tdata = toml.dumps(data)
# print(str(tdata))


def get_benchmark_data():
    return '''
[[b]]
a = 1
b = "cyberdog"
c = true
d = 0.1

[[b]]
a = 2
b = "robotlab"
c = false
d = 0.2

[a]
a = 1
b = "cyberdog"
c = true
d = 0.1
	'''

if __name__ == '__main__':
    data = get_benchmark_data()
    print(data)
